### PR TITLE
Updated pom.xml with Swagger UI

### PR DESCRIPTION
**Pull request by sukantsondhi**
Added Swagger UI Dependency to check the documentation for the Springboot REST API.

### CODE REVIEW

**Review by cmendible — COMMENTED** [review]
If this is needed, I think we should add it as part of the solution provided here: https://github.com/microsoft/CopilotHackathon/tree/main/completesolution/springboot/copilot-demo

@dsanchor any thoughts on this?

**Comment by dsanchor** [comment]
> If this is needed, I think we should add it as part of the solution provided here: https://github.com/microsoft/CopilotHackathon/tree/main/completesolution/springboot/copilot-demo
> 
> @dsanchor any thoughts on this?
Looks good to me. I recommend  to set the version to the latest: 2.3.0.

@sukantsondhi could you please update the version and replicate the change in both the exercisefile and the completesolution as suggested by @cmendible? Thanks

**Comment by sukantsondhi** [comment]
> > If this is needed, I think we should add it as part of the solution provided here: https://github.com/microsoft/CopilotHackathon/tree/main/completesolution/springboot/copilot-demo
> > @dsanchor any thoughts on this?
> 
> Looks good to me. I recommend to set the version to the latest: 2.3.0.
> 
> @sukantsondhi could you please update the version and replicate the change in both the exercisefile and the completesolution as suggested by @cmendible? Thanks

All done!! Added it to both

**Review by cmendible — APPROVED** [review]
LGTM

**Pull request merged**
